[workspace]
members = [".", "consumer"]
default-members = ["consumer"]
resolver = "2"

[package]
name = "servir"
version = "0.1.0"
edition = "2024"

[features]
default = ["telemetry", "auth"]
telemetry = ["dep:tracing-subscriber", "dep:tracing-appender"]
auth = [
    "dep:sqlx",
    "dep:argon2",
    "dep:jsonwebtoken",
    "dep:uuid",
    "dep:getrandom",
    "dep:hex",
]

[dependencies]
axum = "0.8"
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tower-http = { version = "0.6", features = ["trace", "request-id", "uuid"] }
tokio = { version = "1", features = ["net", "rt"] }
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "fmt",
    "json",
], optional = true }
tracing-appender = { version = "0.2", optional = true }
sqlx = { version = "0.8", features = [
    "sqlite",
    "runtime-tokio",
    "macros",
    "migrate",
], optional = true }
argon2 = { version = "0.5", features = ["std"], optional = true }
jsonwebtoken = { version = "10", features = ["rust_crypto"], optional = true }
uuid = { version = "1", features = ["v4"], optional = true }
getrandom = { version = "0.4", optional = true }
hex = { version = "0.4", optional = true }

tower = { version = "0.5" }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
tower = { version = "0.5", features = ["util"] }

[[example]]
name = "echo_server"
required-features = ["telemetry"]
