[package]
name = "echo-server"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "echo-server"
path = "src/main.rs"

[dependencies]
servir = { path = ".." }
axum = "0.8"
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.8", features = [
    "sqlite",
    "runtime-tokio",
    "macros",
    "migrate",
] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
